### ISSUE TITLE
Error: TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by atul2387** [SpectralOps/spectral-github-action#15]
Hello team, we have been getting the similar error as mentioned in the https://github.com/SpectralOps/spectral-github-action/issues/9 whenver Dependabot open a PR to upgrade the packages. How do we resolve this issue permanently? 

My Error:

> Run spectralops/spectral-github-action@v4
  with:
    spectral-args: scan --ok --fail-on-error --exclude-tags=low,informational
  env:
    SPECTRAL_DSN: 
Invalid URL
Waiting 16 seconds before trying again
Invalid URL
Error: TypeError [ERR_INVALID_URL]: Invalid URL

**Comment by guylev008** [comment]
Hi @atul2387 
Dependabot can't access Github actions secrets. you can see the solution [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets).
